name: Deploy to GitHub Pages

on:
  push:
    branches: 'main' # or whichever branch you want to deploy from
  schedule:
    # This is every hour at 40 minutes past
    - cron: '40 */1 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'

          EVIDENCE_SOURCE__system_phase_reference__authenticator: ${{ secrets.EVIDENCE_SOURCE__system_phase_reference__authenticator }}
          EVIDENCE_SOURCE__system_phase_reference__location: ${{ secrets.EVIDENCE_SOURCE__system_phase_reference__location }}
          EVIDENCE_SOURCE__system_phase_reference__client_email: ${{ secrets.EVIDENCE_SOURCE__system_phase_reference__client_email }}
          EVIDENCE_SOURCE__system_phase_reference__private_key: ${{ secrets.EVIDENCE_SOURCE__system_phase_reference__private_key }}
          EVIDENCE_SOURCE__system_phase_reference__project_id: ${{ secrets.EVIDENCE_SOURCE__system_phase_reference__project_id }}

        run: |
          npm run sources
          npm run buildPages

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/${{ github.event.repository.name }}'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
